### ISSUE TITLE
Reading all data sometimes requires socket to close

### ISSUE THREAD

**Issue by ugexe** [jnthn/p6-io-socket-async-ssl#10]
If I run (with PR #9):
`perl6 -Ilib -e 'use IO::Socket::Async::SSL; my $conn = await IO::Socket::Async::SSL.connect("httpbin.org", 443); $conn.print("GET / HTTP/1.1\r\nHost: httpbin.org\r\n\r\n"); react { whenever $conn { .print }; }; $conn.close'`
content gets printed up to `</html`, at which point I have to wait for the connection to timeout before receiving the final `>`. Adding a `Connection: close` also works around this.

If I run (with PR #9):
`perl6 -Ilib -e 'use IO::Socket::Async::SSL; my $conn = await IO::Socket::Async::SSL.connect("httpbin.org", 443); $conn.print("GET / HTTP/1.1\r\nHost: httpbin.org\r\n\r\n"); react { whenever $conn { .print }; }; $conn.close'`
(same as before, but to `/ip`)
nothing gets printed until the connection gets closed via timeout.

**Comment by jnthn** [comment]
The two code examples look the same to me after five readings; did I really manage to miss it every time or are they the same? :-)

As to the issue - this would happen just to same with `IO::Socket::Async`, I'd expect. We can't know there's nothing more coming, and we can't normalize without knowing what the next codepoint will be, unless we see a control and then we know we can just spit it out unconditionally since nothing ever combines with a control. This isn't a bug, it's just a consequence of a `Str` being normalized.

This doesn't seem problematic to me: if you're making a super-cheaty HTTP client then `Connection: close` is fine and if you're making a non-cheaty one you have to implement it in binary mode (to cope with images etc.) and handle `content-length` properly anyway.

Unless there's something more than just the final char being delayed here, this counts as "working as designed", I think.

**Comment by jnthn** [comment]
This is why the example in the README used HTTP/1.0, fwiw. :-)

**Comment by ugexe** [comment]
Gah you're right, the second one should have said `GET /ip HTTP/1.1`

I also totally forgot to do `whenever $conn.Supply(:bin)`, which of course is the proper way.
