### ISSUE TITLE
how to specify ssl_ciphers

### ISSUE THREAD

**Issue by ufobat** [jnthn/p6-io-socket-async-ssl#25]
How can one specify the ciphers which should be used. According to my understanding this is neccessarey to block the blacklisted ciphers for http/2: https://http2.github.io/http2-spec/#BadCipherSuites

**Comment by jnthn** [comment]
So far as HTTP/2.0 goes, the RFC says an implementation *MAY* blacklist them, so it's not a requirement.

So far, there's no way to do that with this module. The `IO::Socket::SSL` module doesn't seem to do it either, alas, so it'll need a bit of figuring out.

**Comment by ufobat** [comment]
Just as an additional comment:
Not sure if I did something wrong, maybe my self signed certificate is somehow wrong, but my Firefox browser as well as my Chrome browser does block a Cro HTTP/2 only Service. And I think because of this part of the http/2 specification.

**Comment by jnthn** [comment]
Yes, they indeed to enforce that bit of the specification. It turns out things are somewhat more involved that just providing a way to set the cipher list (which is now implemented); to use the ciphers that Chrome wants (probably Firefox too) needs some additional setup work to support key exchanges. Along the way I put in support for disabling compression and renegotiation, as well as preferring the server's cipher list's order, which are all things that the spec requires and other HTTP servers are doing.

**Comment by jnthn** [comment]
Implemented the bits needed for DH and ECDH key exchange. We've verified that, together with setting an appropriate cipher list, modern Chrome and Firefox versions are now happy. I just uploaded a 0.6 release to CPAN with these improvements.
